language: python
cache: pip
sudo: false

# Test environments
matrix:
  include:
   - env: TOXENV=py36
     python: 3.6
#   - env: TOXENV=py37
#     python: 3.7
   - env: TOXENV=flake8
     python: 3.6


# Package installation
install:
  - pip install tox codecov

# Run tests
script:
  tox

# Register code coverage in coveralls
after_success:
  codecov